version: '3.8'
services:
  auth:
    build:
      context: .
    container_name: auth
    depends_on:
      - auth-DB
    environment:
      DB_URL: auth-DB/auth-DB1
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8003:8080"
  auth-DB:
    image: 'mysql:latest'
    container_name: auth-DB1
    volumes:
      - dbData:/var/lib/mysql
    environment:
      MYSQL_DATABASE: auth-DB1
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
volumes:
  dbData: